development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: devblog
  username: postgres
  password: letmein
  host: localhost
  encoding: utf8
  port: 5432

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: devblog
  username: postgres
  password: letmein
  host: localhost
  encoding: utf8
  port: 5432

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: devblog
  username: postgres
  password: letmein
  host: localhost
  encoding: utf8
  port: 5432